Bugfix/changelog template syntax
deadlock-wiki/deadbot pull request #41
Opened 2024-09-25 02:15 UTC by Surxe

Corrects {Template} syntax to {{Template}} in changelog parser

2024-09-26 15:53 UTC, hassayag requested changes

2024-09-26 15:53 UTC, hassayag commented on src/parser/parsers/changelogs.py
> +                        icon = "{{AbilityIcon|Ability="+resource_name+"|Size=20}}"
The format of ability icon looks to be `{{AbilityIcon|Siphon Life|Abrams}}`

2024-09-27 23:55 UTC, Surxe commented
Taking the opportunity to transition this to a restructuring of changelog parser; feature may be more descriptive than bugfix.

2024-09-28 10:55 UTC, hassayag reviewed
If you put one of these changelogs into the wiki, does it render what you would expect with icons, links, etc.

2024-09-28 17:55 UTC, Surxe commented
> If you put one of these changelogs into the wiki, does it render what you would expect with icons, links, etc.

not yet

2024-10-17 02:01 UTC, B13rg commented
Okay, squashed the develop branch on and cleaned up my changes.
I tried running a generate, but I hit an error.  I have the same error on develop, so my test is nothing to go by

error:
```
File "/repo/src/parser/parsers/ability_ui.py", line 48, in run
deadbot-1  |     raise Exception(f'[ERROR] Failed to parse ui for ability {ability["Key"]}', e)
deadbot-1  | Exception: ('[ERROR] Failed to parse ui for ability ability_nano_shadow_step', Exception('No localized string for key MeleeAttackSpeedBonus_label')
```

2024-10-17 02:06 UTC, B13rg commented
I can test with just doing changelogs, got it to generate!

2024-10-23 02:01 UTC, Surxe commented
Closing. #84 is opening in its place

2024-10-23 02:01 UTC, closed without merging