Feature/python-fy decompile script
deadlock-wiki/deadbot pull request #43
Opened 2024-09-26 00:33 UTC by B13rg

This converts the decompile process from a sh script to a python script.
This should make it easier to update, and less platform dependent.

It works by reading values from ENV vars (like the script) and calling `os.system()` for external commands.
The copy commands could be replaced by `shutil`, but it's the only place file are directly copied instead of read-in then exported.

I extracted functions from `localization` and `kv3_to_json` python files, so they can be called like before or through importing.

2024-09-28 11:21 UTC, hassayag requested changes
Bash script was getting out of hand, good call. Added a couple missing dotenv calls which I needed to get mine working.

2024-09-28 11:21 UTC, hassayag commented on src/parser/decompiler/decompile.py
While we are here, I think the `decompiler` fits better a folder above (`src/decompiler`), as it is its own independent process that should live at the same level as the parser and bot code

2024-10-02 01:12 UTC, B13rg commented on src/parser/decompiler/decompile.py
Moved it to it's own directory like you suggested.
Also moved the `kv3_to_json.py` script to the `utils` directory

2024-10-02 01:12 UTC, B13rg commented on src/parser/decompiler/localization.py
> +    process_localization_files(input_folder, output_folder)
Removed!  Moved all cli stuff to `deadbot.py`

2024-10-02 01:12 UTC, B13rg commented on src/parser/decompiler/kv3_to_json.py
> +    process_file(sys.argv[1], sys.argv[2])
Done!

2024-10-02 01:52 UTC, B13rg commented
Will have to figure out merge timing with #41 and #49 , I might just wait until after those because so much moves around

2024-10-02 05:59 UTC, B13rg commented
Going to break this up into multiple PRs

2024-10-02 07:06 UTC, B13rg commented
Okay!
First pass is in https://github.com/deadlock-wiki/deadbot/pull/51

2024-10-03 00:32 UTC, closed without merging