83 skip decompile step if local version matches the already decompiled version
deadlock-wiki/deadbot pull request #86
Opened 2024-10-24 02:21 UTC by B13rg

#83 

compares the entire file, so if any of the entries change it'll go through the decompile process.
also added a --force flag in case one want to decompile anyway

2024-10-24 02:42 UTC, B13rg commented
Example output:
```
❯ docker-compose -f ./docker-compose-local.yml up test1                                                   ─╯
[+] Building 0.0s (0/0)                                                                       docker:default
[+] Running 1/0
 ✔ Container deadbot-test1-1  Created                                                                   0.0s 
Attaching to test1-1
test1-1  | Decompiling source files...
test1-1  | version.txt and steam.inf have the same content.
test1-1  | ! Skipping Parser !
test1-1  | ! Skipping Changelogs !
test1-1  | ! Skipping DeadBot !
test1-1  | 
test1-1  | Done!
test1-1 exited with code 0
```

2024-10-25 21:36 UTC, Surxe commented
@B13rg is this ready to be reviewed? If so, please request review from at least Saag :)

2024-10-26 11:02 UTC, hassayag requested changes
👌

2024-10-26 11:02 UTC, hassayag commented on docker-compose-testing.yml
Is this just for manual testing?

2024-10-26 18:30 UTC, B13rg commented on docker-compose-testing.yml
Sort of?  It's how I've been testing the env vars, but it's not exactly very useful on it's own....
I'll just remove it!

2024-10-26 18:56 UTC, B13rg commented on src/decompiler/decompile.py
> +        print('version.txt and steam.inf have the same content.')
Done!
I added a helper func in the utils folder to parse the config file into a dict

2024-10-26 18:57 UTC, B13rg commented on src/decompiler/decompile.py
> +        DECOMPILER_CMD (str): The command used to run the decompiler.
Done!  Also updated readme with flag

2024-10-26 19:02 UTC, B13rg commented
Should be all ready to go!

2024-10-26 21:47 UTC, hassayag approved these changes

2024-10-27 00:29 UTC, merged